// Generates supabase/migrations/0002_seed_properties.sql from the static
// listings in lib/properties.ts so the existing portfolio lands in the
// database on first setup.
//
//   node scripts/generate-seed.mjs
//
import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const { staticProperties } = await import("../lib/properties.ts")

const lit = (v) => (v == null ? "null" : `'${String(v).replace(/'/g, "''")}'`)
const num = (v) => (v == null ? "null" : String(v))
const bool = (v) => (v ? "true" : "false")
const json = (v) => `${lit(JSON.stringify(v))}::jsonb`

const cols = [
  "slug", "type", "agent", "published", "price", "currency", "negotiable",
  "price_on_request", "sold", "is_new", "previous_price", "bedrooms",
  "bathrooms", "built_area", "lot_size", "lot_unit", "location", "map_query",
  "title", "short_description", "description", "highlights", "images",
  "sort_order", "created_by",
]

const rows = staticProperties.map((p, i) =>
  `(${[
    lit(p.slug), lit(p.type), lit(p.agent), "true",
    num(p.price), lit(p.currency), bool(p.negotiable), bool(p.priceOnRequest),
    bool(p.sold), bool(p.isNew), num(p.previousPrice), num(p.bedrooms),
    num(p.bathrooms), num(p.builtArea), num(p.lotSize), lit(p.lotUnit),
    json(p.location), lit(p.mapQuery), json(p.title), json(p.shortDescription),
    json(p.description), json(p.highlights), json(p.images),
    String(i), lit(p.agent),
  ].join(", ")})`
)

const sql = `-- Seed: the listings that were hard-coded in lib/properties.ts.
-- Generated by scripts/generate-seed.mjs — re-running is safe (skips
-- slugs that already exist so admin edits are never overwritten).

insert into public.properties
  (${cols.join(", ")})
values
${rows.join(",\n")}
on conflict (slug) do nothing;
`

const out = join(here, "..", "supabase", "migrations", "0002_seed_properties.sql")
writeFileSync(out, sql)
console.log(`Wrote ${rows.length} listings to ${out}`)
